**DATA PREPARATION**

In [ ]:
import numpy as np
import pandas as pd
import xlrd
import csv
import matplotlib.pyplot as plt

import os
print(os.listdir("/content/drive/MyDrive/SKC"))

['kddcup.data', 'KDDCup99.csv', 'archive.zip', 'archive2.zip']

In [ ]:
class config:
    kdd99train='/content/drive/MyDrive/SKC/kddcup.data'
    kdd99test='/content/drive/MyDrive/SKC/KDDCup99.csv'
def attack_class(train):
    train.loc[(train['label'].isin(['back.','land.','neptune.','pod.','smurf.','teardrop.'])),'label_type']='DOS'
    train.loc[train['label'].isin(['ipsweep.','nmap.','portsweep.','satan.']),'label_type']='Probing'
    train.loc[train['label'].isin(['ftp_write.','guess_passwd.','imap.','multihop.','phf.','spy.','warezclient.','warezmaster.']),'label_type']='R2L'
    train.loc[train['label'].isin(['buffer_overflow.','loadmodule.','perl.','rootkit.']),'label_type']='U2R'
    train.loc[train['label']=='normal.','label_type']='Normal'
    return train

def attack_class2(train):
    train.loc[(train['label'].isin(['back','land','neptune','pod','smurf','teardrop'])),'label_type']='DOS'
    train.loc[train['label'].isin(['ipsweep','nmap','portsweep','satan']),'label_type']='Probing'
    train.loc[train['label'].isin(['ftp_write','guess_passwd','imap','multihop','phf','spy','warezclient','warezmaster']),'label_type']='R2L'
    train.loc[train['label'].isin(['buffer_overflow','loadmodule','perl','rootkit']),'label_type']='U2R'
    train.loc[train['label']=='normal','label_type']='Normal'
    return train


cleanup_nums = {"protocol_type":     {"tcp": 1, "icmp": 2, "udp": 3},
                "service": {"vmnet": 1, "smtp": 2, "ntp_u":3, "shell":4, "kshell":5, "aol":6, "imap4":7, "urh_i":8, "netbios_ssn":9,
                           "tftp_u":10, "mtp":11, "uucp":12, "nnsp":13, "echo":14, "tim_i":15, "ssh":16, "iso_tsap":17, "time":18,
                           "netbios_ns":19,"systat":20, "hostnames":21, "login":22, "efs":23, "supdup":24, "http_8001":25, "courier":26,
                           "ctf":27,"finger":28,"nntp":29,"ftp_data":30,"red_i":31,"ldap":32,"http":33,"ftp":34,"pm_dump":35,"exec":36,
                           "klogin":37,"auth":38,"netbios_dgm":39,"other":40,"link":41,"X11":42,"discard":43,"private":44,"remote_job":45,
                           "IRC":46,"daytime":47,"pop_3":48,"pop_2":49,"gopher":50,"sunrpc":51,"name":52,"rje":53,"domain":54,"uucp_path":55,
                           "http_2784":56,"Z39_50":57,"domain_u":58,"csnet_ns":59,"whois":60,"eco_i":61,"bgp":62,"sql_net":63,"printer":64,
                           "telnet":65,"ecr_i":66,"urp_i":67,"netstat":68,"http_443":69,"harvest":70},
               "flag":{"RSTR":1,"S3":2,"SF":3,"RSTO":4,"SH":5,"OTH":6,"S2":7,"RSTOS0":8,"S1":9,"S0":10,"REJ":11},
               "label_type":{"Normal":1,"DOS":2,"Probing":3,"R2L":4,"U2R":5}}
attack_map={"label_type":{"Normal":1,"DOS":2,"Probing":3,"R2L":4,"U2R":5}}

column = ["duration","protocol_type","service","flag","src_bytes","dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins","logged_in","lnum_compromised","lroot_shell","lsu_attempted","lnum_root","lnum_file_creations","lnum_shells","lnum_access_files","lnum_outbound_cmds","is_host_login","is_guest_login","count","srv_count","serror_rate","srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate","diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count","dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate","dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate","dst_host_rerror_rate","dst_host_srv_rerror_rate","label"]

In [ ]:
print("train data loading")
train = pd.read_csv(config.kdd99train)
train.columns= column
train.insert(0,'label_type','NAN')
#Mapping dengan Kategori data dalam dataset

datapre = train
#Replacing encoded data dalam dataset
datapre.replace(cleanup_nums, inplace=True)

train = attack_class(datapre)

train['label_type'].value_counts()

train.replace(attack_map, inplace=True)

train.drop('label', axis = 1, inplace = True)
train.head()

train data loading

   label_type  duration  ...  dst_host_rerror_rate  dst_host_srv_rerror_rate
0           1         0  ...                   0.0                       0.0
1           1         0  ...                   0.0                       0.0
2           1         0  ...                   0.0                       0.0
3           1         0  ...                   0.0                       0.0
4           1         0  ...                   0.0                       0.0

[5 rows x 42 columns]

In [ ]:
print("test data loading")
test = pd.read_csv(config.kdd99test)
test.insert(0,'label_type','NAN')

datapre = test
#Replacing encoded data dalam dataset
datapre.replace(cleanup_nums, inplace=True)

test = attack_class2(datapre)

test['label_type'].value_counts()

test.replace(attack_map, inplace=True)

test.drop('label', axis = 1, inplace = True)
test.head()

test data loading

   label_type  duration  ...  dst_host_rerror_rate  dst_host_srv_rerror_rate
0           1         0  ...                   0.0                       0.0
1           1         0  ...                   0.0                       0.0
2           1         0  ...                   0.0                       0.0
3           1         0  ...                   0.0                       0.0
4           1         0  ...                   0.0                       0.0

[5 rows x 42 columns]

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898430 entries, 0 to 4898429
Data columns (total 42 columns):
 #   Column                       Dtype
---  ------                       -----
 0   label_type                   int64
 1   duration                     int64
 2   protocol_type                int64
 3   service                      int64
 4   flag                         int64
 5   src_bytes                    int64
 6   dst_bytes                    int64
 7   land                         int64
 8   wrong_fragment               int64
 9   urgent                       int64
 10  hot                          int64
 11  num_failed_logins            int64
 12  logged_in                    int64
 13  lnum_compromised             int64
 14  lroot_shell                  int64
 15  lsu_attempted                int64
 16  lnum_root                    int64
 17  lnum_file_creations          int64
 18  lnum_shells                  int64
 19  lnum_access_files            int64
 20  lnum_outbound_cmds           int64
 21  is_host_login                int64
 22  is_guest_login               int64
 23  count                        int64
 24  srv_count                    int64
 25  serror_rate                  float64
 26  srv_serror_rate              float64
 27  rerror_rate                  float64
 28  srv_rerror_rate              float64
 29  same_srv_rate                float64
 30  diff_srv_rate                float64
 31  srv_diff_host_rate           float64
 32  dst_host_count               int64
 33  dst_host_srv_count           int64
 34  dst_host_same_srv_rate       float64
 35  dst_host_diff_srv_rate       float64
 36  dst_host_same_src_port_rate  float64
 37  dst_host_srv_diff_host_rate  float64
 38  dst_host_serror_rate         float64
 39  dst_host_srv_serror_rate     float64
 40  dst_host_rerror_rate         float64
 41  dst_host_srv_rerror_rate     float64
dtypes: float64(15), int64(27)
memory usage: 1.5 GB

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494020 entries, 0 to 494019
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   label_type                   494020 non-null  int64
 1   duration                     494020 non-null  int64
 2   protocol_type                494020 non-null  int64
 3   service                      494020 non-null  int64
 4   flag                         494020 non-null  int64
 5   src_bytes                    494020 non-null  int64
 6   dst_bytes                    494020 non-null  int64
 7   land                         494020 non-null  int64
 8   wrong_fragment               494020 non-null  int64
 9   urgent                       494020 non-null  int64
 10  hot                          494020 non-null  int64
 11  num_failed_logins            494020 non-null  int64
 12  logged_in                    494020 non-null  int64
 13  lnum_compromised             494020 non-null  int64
 14  lroot_shell                  494020 non-null  int64
 15  lsu_attempted                494020 non-null  int64
 16  lnum_root                    494020 non-null  int64
 17  lnum_file_creations          494020 non-null  int64
 18  lnum_shells                  494020 non-null  int64
 19  lnum_access_files            494020 non-null  int64
 20  lnum_outbound_cmds           494020 non-null  int64
 21  is_host_login                494020 non-null  int64
 22  is_guest_login               494020 non-null  int64
 23  count                        494020 non-null  int64
 24  srv_count                    494020 non-null  int64
 25  serror_rate                  494020 non-null  float64
 26  srv_serror_rate              494020 non-null  float64
 27  rerror_rate                  494020 non-null  float64
 28  srv_rerror_rate              494020 non-null  float64
 29  same_srv_rate                494020 non-null  float64
 30  diff_srv_rate                494020 non-null  float64
 31  srv_diff_host_rate           494020 non-null  float64
 32  dst_host_count               494020 non-null  int64
 33  dst_host_srv_count           494020 non-null  int64
 34  dst_host_same_srv_rate       494020 non-null  float64
 35  dst_host_diff_srv_rate       494020 non-null  float64
 36  dst_host_same_src_port_rate  494020 non-null  float64
 37  dst_host_srv_diff_host_rate  494020 non-null  float64
 38  dst_host_serror_rate         494020 non-null  float64
 39  dst_host_srv_serror_rate     494020 non-null  float64
 40  dst_host_rerror_rate         494020 non-null  float64
 41  dst_host_srv_rerror_rate     494020 non-null  float64
dtypes: float64(15), int64(27)
memory usage: 158.3 MB

In [ ]:
#Cross validation
#from sklearn import cross_validation
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

train_data = train.values
features_train = train_data[:,1:42]
labels_train = train_data[:,0]

test_data = test.values
features_test = test_data[:,1:42]
labels_test = test_data[:,0]

In [ ]:
#Naive Bayes Classifier
from sklearn import metrics
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error

In [ ]:
#Naive Bayes Classifier
clf = GaussianNB()

clf.fit(features_train, labels_train)
prediction = clf.predict(features_test)

In [ ]:
#Confussion Matrix
matrix = confusion_matrix(labels_test, prediction)
print(matrix)

[[ 65254  27200    783     96   3944]
 [  2310 388900      2      0    246]
 [   975   2617     76      0    439]
 [   298     37     96      5    690]
 [     7      4      0      0     41]]

In [ ]:
from sklearn.metrics import f1_score as f1
from sklearn.metrics import accuracy_score as acc_score
from sklearn.metrics import precision_score as prec
from sklearn.metrics import recall_score as recall

#evaluasi
print("Accuracy  : ", acc_score(labels_test,prediction)*100," %")
print("F1-Score  : ", f1(labels_test,prediction, average='macro')*100," %")
print("Precision : ", prec(labels_test,prediction, average='macro')*100," %")
print("Recall    : ", recall(labels_test,prediction, average='macro')*100," %")

Accuracy  :  91.95498157969313  %
F1-Score  :  35.97856616932902  %
Precision :  40.2624167012361  %
Recall    :  49.51357061536904  %

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).